version: '3.7'

services:
  cyklaiskane-app:
    environment:
      TILES_BG_URL: https://cyklaiskane-tiles.travelvu.io/styles/bg/{z}/{x}/{y}.png
      TILES_TS_URL: https://cyklaiskane-tiles.travelvu.io/styles/velo/{z}/{x}/{y}.png
    networks:
      - traefik
      - default
    deploy:
      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.cyklaiskane.rule=Host(`cyklaiskane.travelvu.io`, `cyklaiskane.se`, `www.cyklaiskane.se`)"
        - "traefik.http.routers.cyklaiskane.service=cyklaiskane"
        - "traefik.http.routers.cyklaiskane.entrypoints=websecure"
        - "traefik.http.routers.cyklaiskane.tls=true"
        - "traefik.http.services.cyklaiskane.loadbalancer.server.port=8000"

  cyklaiskane-cache:
    image: trivectortraffic/cyklaiskane-varnish
    #command:
    #  - "sleep"
    #  - "1d"
    networks:
      - traefik
      - default
    deploy:
      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.cyklaiskane-tiles.rule=Host(`cyklaiskane-tiles.travelvu.io`)"
        - "traefik.http.routers.cyklaiskane-tiles.service=cyklaiskane-tiles"
        - "traefik.http.routers.cyklaiskane-tiles.entrypoints=websecure"
        - "traefik.http.routers.cyklaiskane-tiles.tls=true"
        - "traefik.http.services.cyklaiskane-tiles.loadbalancer.server.port=80"

  tileserver:
    image: trivectortraffic/cyklaiskane-tileserver


networks:
  default:
    driver: overlay
  traefik:
    external: true
