version: '3.7'


services:
  app:
    image: velociped
    environment:
      POSTGRES_DSN: 'postgres://velociped:foobar@db/velociped'
    ports:
      - 8008:8000
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.cyklaiskane.rule=Host(`cyklaiskane.travelvu.io`)"
      - "traefik.http.routers.cyklaiskane.entrypoints=https"
      - "traefik.http.routers.cyklaiskane.tls=true"
      - "traefik.http.services.cyklaiskane.loadbalancer.server.port=8000"


  db:
    image: pgrouting/pgrouting:12-3.0-2.6.3
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - 5433:5432

  admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80



volumes:
  db-data: {}
  pgadmin-data: {}


networks:
  default:
    driver: bridge
  travelvu_internal:
    external: true
