version: '3.7'


services:
  cyklaiskane-app:
    image: trivectortraffic/velociped
    depends_on:
      - db
    environment:
      - POSTGRES_DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - LM_CLIENT_ID
      - LM_CLIENT_SECRET

  cyklaiskane-cache:
    image: varnish:stable
    environment:
      - VARNISH_SIZE=512M
    #volumes:
    #  - type: tmpfs
    #    target: /var/lib/varnish
    #    tmpfs:
    #      exec: true
    #      size: 134217728

  tileserver:
    image: trivectortraffic/tileserver-gl:v3.0.0

  db:
    image: pgrouting/pgrouting:12-3.0-2.6.3
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data:cached
    ports:
      - 5433:5432



volumes:
  db-data: {}
